apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-app
  labels:
    app: ts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-app
  template:
    metadata:
      labels:
        app: ts-app
    spec:
      containers:
        - name: ts-app
          image: ts-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
