apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-app
  annotations:
    redeploy-timestamp: "2025-05-12T15:30:00"  # <- Changed timestamp
  labels:
    app: ts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-app
  template:
    metadata:
      labels:
        app: ts-app
        version: "v2"  # <- Added version label
    spec:
      containers:
        - name: ts-app
          image: ts-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

